version: '3.8'

services:
  #database section
  open-identity-db: 
    image: postgres:alpine3.16

  open-gmail-db:
    image: postgres:alpine3.16
    
  open-drive-db:
    image: postgres:alpine3.16  

  distributed-cache:
    image: redis

  #infrastructure section
  pgadmin:
    image: dpage/pgadmin4

  # portainer:
  #   image: portainer/portainer-ce

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:7.17.2

  #microservices api section

#network section
networks:
  default:
    name: open_school_microservices
    driver: bridge

#volumes section
volumes:
  open_identity_data:
    name: identity_data
  open_drive_data:
    name: file_manager_data
  open_gmail_data:
    name: mailbox_data
  open_pgadmin_data:
    name: pgadmin_data



